### ISSUE TITLE
Hard coded resolution

### ISSUE THREAD

**Issue by lukashou-agh** [nemote95/crop-row-detection#1]
First of all, I would like to say thank you, I really enjoy reading your code and simple and well-structured. I realize that you use specific dataset, but the problem I found is that you cannot feed your own images without resizing them to 320x240, which I changed in my code quite easily, but then when you produce a perspective you use [140, 171] and I don't really see where those numbers come from. Could you give me some hints? I will send a pull request when I'll be good to go with this improvement.

**Comment by nemote95** [comment]
Thanks for your question. it is basically the region of interest that I
selected for perspective transformation. I just made some changes to make it better and hopefully understandable.
